version: "3"
services:
  dynamodb:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb
    ports:
      - 8000:8000

  app:
    build: .
    ports:
      - 9000:8080
    environment:
      IS_LOCAL: true
