services:
  dynamodb:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD-SHELL", "db_status=\"$(curl -s http://localhost:8000 -w ''%{http_code}'' -o /dev/null)\"; [ \"$db_status\" == \"400\" ] && exit 1 || exit 0"]
      interval: 1s
      timeout: 10s
      retries: 10

  dynamodb-create-table:
    image: amazon/aws-cli
    depends_on:
      dynamodb:
        condition: service_healthy
    entrypoint: /bin/sh
    command: create-table.sh
    working_dir: /app
    volumes:
      - ./dynamodb:/app

  lambda:
    depends_on:
      dynamodb:
        condition: service_healthy
    build: .
    ports:
      - 9000:8080
    environment:
      IS_LOCAL: 'true'
      DYNAMODB_HOST: dynamodb
